files:
- generatedChecksum: B9388144EA8C18C396F2DB6CC40DCB4D
  logicalPath: config\sam_g55_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B9388144EA8C18C396F2DB6CC40DCB4D
- generatedChecksum: 47EB5DE9A18A2267F00B3D091FE80249
  logicalPath: config\sam_g55_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47EB5DE9A18A2267F00B3D091FE80249
- generatedChecksum: 75D1133FB71DC8EA5D01AFAC6E20C37F
  logicalPath: config\sam_g55_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 75D1133FB71DC8EA5D01AFAC6E20C37F
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_g55_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5E1519A6B468C6C2F3C6FBA9C25E632C
  logicalPath: config\sam_g55_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5E1519A6B468C6C2F3C6FBA9C25E632C
- generatedChecksum: 4DE159F616B56E2CEDEBEF156269B15C
  logicalPath: config\sam_g55_xpro\peripheral\cmcc
  name: plib_cmcc.c
  physicalPath: peripheral\cmcc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4DE159F616B56E2CEDEBEF156269B15C
- generatedChecksum: AA664C7023E156B2C6430CCBBAA479D8
  logicalPath: config\sam_g55_xpro\peripheral\efc
  name: plib_efc.c
  physicalPath: peripheral\efc
  security: NON_SECURE
  type: SOURCE
  userChecksum: AA664C7023E156B2C6430CCBBAA479D8
- generatedChecksum: 82DB586983B5AAB59652A92294FA6F35
  logicalPath: config\sam_g55_xpro\peripheral\flexcom\usart
  name: plib_flexcom0_usart.c
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 82DB586983B5AAB59652A92294FA6F35
- generatedChecksum: 8CAFE006F98B6C349F935627D74BC21A
  logicalPath: config\sam_g55_xpro\peripheral\flexcom\usart
  name: plib_flexcom7_usart.c
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8CAFE006F98B6C349F935627D74BC21A
- generatedChecksum: 2189A0A4CD577ECC9D357C243E978F46
  logicalPath: config\sam_g55_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2189A0A4CD577ECC9D357C243E978F46
- generatedChecksum: 16DFB41C3FE7A1FB309DEFEF96C4F351
  logicalPath: config\sam_g55_xpro\peripheral\pio
  name: plib_pio.c
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16DFB41C3FE7A1FB309DEFEF96C4F351
- generatedChecksum: D0B9515FE0B37F7C2FA93CC389639356
  logicalPath: config\sam_g55_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D0B9515FE0B37F7C2FA93CC389639356
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\sam_g55_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 33B8AE06998C7673C7C6978BC2B0BFC2
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 33B8AE06998C7673C7C6978BC2B0BFC2
- generatedChecksum: 9C858FD38C5E41BC3F03F88C0F1E682F
  logicalPath: packs\ATSAMG55J19_DFP
  name: atsamg55j19.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 9C858FD38C5E41BC3F03F88C0F1E682F
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 2351FE542BE477802ED7A2D252C9BD68
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: chipid.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2351FE542BE477802ED7A2D252C9BD68
- generatedChecksum: 44AB78DF310309AB58E02DC203F4672A
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: cmcc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 44AB78DF310309AB58E02DC203F4672A
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: 624A16D50759D7A491C523D747764B49
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm4.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 624A16D50759D7A491C523D747764B49
- generatedChecksum: D26DBFD427F5323A7F9490C02EAFB317
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: crccu.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D26DBFD427F5323A7F9490C02EAFB317
- generatedChecksum: 7F26F7827BA86BEDC5F08589B98808F9
  logicalPath: config\sam_g55_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F26F7827BA86BEDC5F08589B98808F9
- generatedChecksum: BFE860AE70C6EF2EA4445C16815178D3
  logicalPath: config\sam_g55_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: BFE860AE70C6EF2EA4445C16815178D3
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_g55_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: 8AF9491AE3E5EB6C332743ED86D15743
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: efc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8AF9491AE3E5EB6C332743ED86D15743
- generatedChecksum: 65971BB9DAA90836587BBEBCA0E00F23
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: flexcom.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 65971BB9DAA90836587BBEBCA0E00F23
- generatedChecksum: 2B7D20BD8633E6C215061D4745D2F334
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: gpbr.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B7D20BD8633E6C215061D4745D2F334
- generatedChecksum: 535F607A292B9BF040DCC67D6F9E6D31
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: i2sc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 535F607A292B9BF040DCC67D6F9E6D31
- generatedChecksum: 7E6B142F8C773CBC3B70314F2FEE35CE
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: matrix.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7E6B142F8C773CBC3B70314F2FEE35CE
- generatedChecksum: 0F97A5EA3F4881D1B9C80521DD236DBF
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: mem2mem.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0F97A5EA3F4881D1B9C80521DD236DBF
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: C58E0A88D8B8AAD4E8BC66091F1F0611
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: pdc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C58E0A88D8B8AAD4E8BC66091F1F0611
- generatedChecksum: B7922F37C8308346497177BA146534D3
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: pdmic.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B7922F37C8308346497177BA146534D3
- generatedChecksum: 76EF458E97535FECBCC1FA614DC456E6
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: pio.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 76EF458E97535FECBCC1FA614DC456E6
- generatedChecksum: 78387EA60F98EE9F5602C2EB8CFEA8B3
  logicalPath: config\sam_g55_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: 78387EA60F98EE9F5602C2EB8CFEA8B3
- generatedChecksum: 95A89CFFC2B67EA718036EF9B8805872
  logicalPath: config\sam_g55_xpro\peripheral\cmcc
  name: plib_cmcc.h
  physicalPath: peripheral\cmcc
  security: NON_SECURE
  type: HEADER
  userChecksum: 95A89CFFC2B67EA718036EF9B8805872
- generatedChecksum: FB046CED42CA3B2AE1895C186571EF71
  logicalPath: config\sam_g55_xpro\peripheral\efc
  name: plib_efc.h
  physicalPath: peripheral\efc
  security: NON_SECURE
  type: HEADER
  userChecksum: FB046CED42CA3B2AE1895C186571EF71
- generatedChecksum: 8D3516DF80F70E6AAD5DEAA2E8515712
  logicalPath: config\sam_g55_xpro\peripheral\flexcom\usart
  name: plib_flexcom0_usart.h
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8D3516DF80F70E6AAD5DEAA2E8515712
- generatedChecksum: 2FEFE9BBE6788C4936C9618BF0946188
  logicalPath: config\sam_g55_xpro\peripheral\flexcom\usart
  name: plib_flexcom7_usart.h
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 2FEFE9BBE6788C4936C9618BF0946188
- generatedChecksum: BA8F8A5199A794E8EBA58B7C48FCF87C
  logicalPath: config\sam_g55_xpro\peripheral\flexcom\usart
  name: plib_flexcom_usart_local.h
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: BA8F8A5199A794E8EBA58B7C48FCF87C
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_g55_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: C5611BD3B756FE509EAB84A7B1A76CAA
  logicalPath: config\sam_g55_xpro\peripheral\pio
  name: plib_pio.h
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: C5611BD3B756FE509EAB84A7B1A76CAA
- generatedChecksum: D6F23CF2C50EA94ED43681C29E79E86A
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: pmc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D6F23CF2C50EA94ED43681C29E79E86A
- generatedChecksum: 2BEFB47A30B0DCE1EB7DB0AE5FD683C8
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2BEFB47A30B0DCE1EB7DB0AE5FD683C8
- generatedChecksum: B9314BCBC9E7C2FC982405D122A1588D
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B9314BCBC9E7C2FC982405D122A1588D
- generatedChecksum: F8AC362B6968276E4337C035603A555C
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: rtt.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F8AC362B6968276E4337C035603A555C
- generatedChecksum: 8B7B5AF8CE2C747A5AAD02FF87455114
  logicalPath: packs\ATSAMG55J19_DFP\pio
  name: samg55j19.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B7B5AF8CE2C747A5AAD02FF87455114
- generatedChecksum: 1AA8C3241AEACA0B64C448738A46C55C
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: spi.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1AA8C3241AEACA0B64C448738A46C55C
- generatedChecksum: CED767FAA3364B72BB2200A5F4F18D2E
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CED767FAA3364B72BB2200A5F4F18D2E
- generatedChecksum: 457832D233EA8DEBD42141842F44A3F3
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 457832D233EA8DEBD42141842F44A3F3
- generatedChecksum: 3448B62FDF48416310C7CED2A0A37D1C
  logicalPath: config\sam_g55_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 3448B62FDF48416310C7CED2A0A37D1C
- generatedChecksum: 073B7D438153114A5C8EAE616A128B2B
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: twi.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 073B7D438153114A5C8EAE616A128B2B
- generatedChecksum: 8B7B8A7EE93BCED296B8E213D66CF0F4
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: udp.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B7B8A7EE93BCED296B8E213D66CF0F4
- generatedChecksum: 4DDDB3B28ED29C489AC276ADA5B2D056
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: uhp.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4DDDB3B28ED29C489AC276ADA5B2D056
- generatedChecksum: 0812F2F5523B9F5702EBA00C1EBF03EA
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: usart.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0812F2F5523B9F5702EBA00C1EBF03EA
- generatedChecksum: EB17C8FB3A76B88680D0A0F38E789E99
  logicalPath: packs\ATSAMG55J19_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMG55J19_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EB17C8FB3A76B88680D0A0F38E789E99
- generatedChecksum: 3107FADFEBAC9D7D26B4DEB81811A4BB
  logicalPath: config\sam_g55_xpro
  name: ATSAMG55J19.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 3107FADFEBAC9D7D26B4DEB81811A4BB
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_g55_xpro;../src/packs/ATSAMG55J19_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_g55_xpro;../src/packs/ATSAMG55J19_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32Global
  delimiter: ''
  key: mdtcm
  security: NON_SECURE
  value: ''
- append: false
  category: C32Global
  delimiter: ''
  key: mitcm
  security: NON_SECURE
  value: ''
- append: false
  category: C32Global
  delimiter: ''
  key: mstacktcm
  security: NON_SECURE
  value: 'false'
sourcePaths: []
